[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install",
  "npm rebuild"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"

[variables]
NODE_ENV = "production"
NITRO_HOST = "0.0.0.0"

[staticAssets]
"public" = "./"
".output/public" = "./"